### ISSUE TITLE
Download element

### ISSUE THREAD

**Issue by Cleanerrr** [terminal42/contao-fineuploader#101]
Hi
I want to use Fine Uploader so that my users can upload certain files. In a protected subpage, the Staff should be able to download these files. With the use of the file upload field in the Contao form, I was able to specify the folder in the File Manager where all files are stored without any problems. After that, I enabled the download of all files from that folder with the Download element. So I marked the folder in the download element and all the files are automatically displayed in the frontend and ready for download. 

My question is why doesn't this work with Fine Uploader? I mark the same folder with it as well, but not a single file is selected after it is uploaded. Is this a bug or simply a flaw? 

Thank you in advance

**Comment by aschempp** [comment]
It most likely does not work because the files are not added to the DBAFS. Not sure if there's such an option?

**Comment by fritzmg** [comment]
There is such an option.
