### ISSUE TITLE
Ungüliges Token Abfrage  - NC / Fineuploader nach Updates

### ISSUE THREAD

**Issue by vaddi22** [terminal42/contao-fineuploader#109]
Hallo,
erst einmal möchte ich sagen, dass die Erweiterungen wirklich klasse sind. Vielen Dank dafür!
Ich möchte auf einen Fehler hinweisen und viell. hat Jemand eine Lösung

1) Der Versand eines Formulars mit NC 2.0.3 und Fineuploader 3.4.10 funktioniert nach den neusten Updates leider nicht mehr.
2) Sobald ein Anhang mitgesendet werden soll erscheint die Contao Fehlermeldung - Ungültiges Anfrage Token - 
3) Wenn man aber im Backend "angemeldet" ist und dann über die Webseite das Formular versendet, funktioniert das versenden einwandfrei. Sobald man sich wieder im Backend abmeldet funktioniert es nicht mehr und es kommt die Fehlermeldung.
4) Ein Downgrade der beiden Erweiterungen brachte leider auch keinen Erfolg.
5) Bis Contao 4.13.36 ohne Updates funktionierte alles einwandfrei.
6) Update auf Contao 4.13.40 und den neusten Versionen vom NC & Fineuploader brachte auch keinen Erfolg.

Leider habe ich mehrere Seiten, wo der NC und der Fineuploader integriert sind und musste diese jetzt alle auf den normalen Contao Upload umbauen. Damit funktioniert der Versand inkl. Anhang.

Viell. hat Jemand einen Rat woran es liegen könnte?
Vielen Dank im voraus...

![ungültiges Token](https://github.com/terminal42/contao-fineuploader/assets/166727029/54c7bf4a-0e9a-4c95-ab60-cfa142908647)

**Comment by fritzmg** [comment]
This is likely an issue in Contao itself (see also https://github.com/contao/contao/issues/7167).
