### ISSUE TITLE
Send file as an attachment in the e-mail

### ISSUE THREAD

**Issue by contaoacademy** [terminal42/contao-fineuploader#112]
I'm not sure if the behaviour of the extension or that of Contao has changed.

I think that previously the uploaded files were sent directly as an e-mail attachment. Since one of the last updates this is no longer the case.

The e-mail now only contains a link to download the file.
Is this behaviour correct or is it a bug?

My setup:
Contao 4.13.44
PHP 8.3.7
FineUploader 3.4.11
Contao standard form (no NC)

**Comment by fritzmg** [comment]
It depends on your upload form field settings. If you enabled **Store uploaded files** then Contao will include a link to the email. If it is not enabled, Contao will attach the file to the email. At least that's how it should be.

**Comment by contaoacademy** [comment]
Thank you @fritzmg . My mistake...

I'm closing the ticket.
