### ISSUE TITLE
No e-mail attachments with fine upload

### ISSUE THREAD

**Issue by lizardat** [terminal42/contao-fineuploader#115]
Contao 5.3.15
NC 2.0.16
Fine Uploader 3.4.13
PHP 8.3

I know this issue is supposed to be closed but I still get the same problem as others before:
fine upload does not attach files to the email (with saving option deselected).

however, all files are correctly uploaded and saved with option selected.
Also files are correctly attached when using the regular file upload form field.

This is an update from Contao 4.13 where attachments via fine uploader were working fine.

**Comment by fritzmg** [comment]
I have just tested it and it works. Please post a screenshot of your fineuploader config and your notification message config.

**Comment by lizardat** [comment]
<img width="1067" alt="Bildschirmfoto 2024-09-23 um 11 30 42" src="https://github.com/user-attachments/assets/93dabb96-3a5f-4766-b685-672d4ee3d599">
<img width="1032" alt="Bildschirmfoto 2024-09-23 um 11 29 56" src="https://github.com/user-attachments/assets/c3e5da82-424a-4778-915b-f3077874a845">

**Comment by fritzmg** [comment]
You need to use `##form_upload_0##` instead of `##form_upload##`. Fineuploader widgets always have multiple values.

**Comment by lizardat** [comment]
Thanks.

**Comment by fritzmg** [comment]
But you are saying you had the same config in Contao 4.13 and NC 1.x and it worked?

**Comment by lizardat** [comment]
yes. ##form_upload## only. no matter how many files.

**Comment by fritzmg** [comment]
In any case, this is not an issue with this extension - closing again in favor of https://github.com/terminal42/contao-notification_center/issues/342
