### ISSUE TITLE
Drop $arrFilesMapper

### ISSUE THREAD

**Issue by qzminski** [terminal42/contao-fineuploader#15]
This can be possibly dropped.

https://github.com/terminal42/contao-fineuploader/blob/master/widgets/FineUploaderBase.php#L30

**Comment by Toflar** [comment]
I think it can.

**Comment by qzminski** [comment]
I don't remember the reason why could it be dropped and I have just noticed it's still used here:

https://github.com/terminal42/contao-fineuploader/blob/master/widgets/FineUploaderBase.php#L276

So maybe we should leave it?

**Comment by Toflar** [comment]
But it’s never used anywhere? Or probably by some class that’s extending it?

**Comment by aschempp** [comment]
Dunno if there are child classes that use it? E.g. for Isotope eCommerce?

**Comment by qzminski** [comment]
Okay so apparently it was in the initial commit of the reworked extension. However, later on its usage has been removed so I think we can safely drop it.

https://github.com/terminal42/contao-fineuploader/commit/d3756e86d1b7f5de580813b730267fd60aff06a3

**Comment by aschempp** [comment]
fine with me :-)
