### ISSUE TITLE
Files not stored in defined UploadFolder

### ISSUE THREAD

**Issue by 47gn** [terminal42/contao-fineuploader#16]
Hi Kamil,

I'm using the Fineuploader via DCA Field in my Backend-Module. After the Upload (i see the path /system/tmp/somefilename.pdf) i try to save. The Files i have uploaded before saving isn't stored in defined Upload Folder. The files stored only in the folder /system/tmp.

Is there something wrong with my configuration? I'm using Contao 3.2.16.

Thanx for your help :)

**Comment by qzminski** [comment]
Please paste your configuration here.

**Comment by 47gn** [comment]
Here is the configuration:

		'files_kunden' => array
		(
			'label'                   => &$GLOBALS['TL_LANG']['tl_tdo_kundenantrag_neu']['files_kunden'],
			'exclude'                 => true,
			'inputType'               => 'fineUploader',
			'eval'                    => array
			(
				'storeFile' => true, // Mandatory to store the file on the server
				'multiple' => true, // Allow multiple files to be uploaded
				// 'uploadFolder' => 'tl_files/energiesued/kundendaten/'.\Input::get('id'), // Upload path (destination folder)
				'uploadFolder' => 'tl_files', // Upload path (destination folder)
				// 'uploaderConfig' => 'debug: true', // Custom uploader configuration (JSON)
				'uploaderLimit' => 4, // Maximum files that can be uploaded
				'addToDbafs' => true, // Add files to the database assisted file system
				'extensions' => $GLOBALS['TL_CONFIG']['uploadTypes'], // Allowed extension types
				'maxlength' => 2048000, // Maximum file size
				'doNotOvewrite' => true, // Do not overwrite files in destination folder

				'chunking' => true, // Enable chunking
				'chunkSize' => 2000000, // Chunk size in bytes

				// You can also use the default features of fileTree widget such as:
				// isGallery, isDownloads

				// The "orderField" attribute is not valid (see #9)
			),
			'sql'                     => "blob NULL"
		),

**Comment by qzminski** [comment]
Do you submit the formular? That is the moment when files are moved to the destination folder.

**Comment by 47gn** [comment]
Yes, i Click "Save" and Save the dataset. When i Look After Save the dataset into the destination folder, it was emoty.

Von meinem iPhone gesendet

Am 28.01.2015 um 18:45 schrieb Kamil Kuzminski <notifications@github.com<mailto:notifications@github.com>>:


Do you submit the formular? That is the moment when files are moved to the destination folder.

-

**Comment by Toflar** [comment]
Does `tl_files` (your `uploadFolder`) even exist? By default it's named `files`.

**Comment by 47gn** [comment]
Hey Yanick,

Yes the diretory „tl_files“ exists. The Contao System was updated from a earlier Version an all Files stores in „tl_files/..“

**Comment by Toflar** [comment]
Any feedback?
