### ISSUE TITLE
Formulargenerator

### ISSUE THREAD

**Issue by Munsio** [terminal42/contao-fineuploader#17]
Hi,

Ich benutz euer Datei Upload script im Contao Formulargenerator und bin drauf gekommen das dort nach dem Hochladen das File nicht zum DBAFS hinzugefügt wird.

Fehlt hier für das Widget eventuell noch in der Configuration der "addToDbafs" Key?

**Comment by Toflar** [comment]
Wir haben im Moment gerade kein Projekt wo wir das benötigen würden, ich hab aber mal den Milestone 1.1 zugewiesen. PR's welcome :)

**Comment by aschempp** [comment]
Siehe auch https://github.com/contao/core/issues/7751

**Comment by qzminski** [comment]
Implemented in a2129b4.
