### ISSUE TITLE
Dateien mit Klammern im Dateinamen werden nicht gespeichert

### ISSUE THREAD

**Issue by mafudelaptu** [terminal42/contao-fineuploader#18]
ich versuche ein Bild mit dem fineuploader im Backend hochzuladen mit dem Dateinamen:  "images (1).jpg"

Es wird erfolgreich in dem system/tmp Ordner kopiert. Wenn ich jedoch auf "Speichern" drücke wird die Datei nicht in den uploadFolder verschoben.

Dateien mit anderen Dateinamen funktionieren.

dca:
  'image' => array(
			'label' => & $GLOBALS['TL_LANG']['tl_modul']['image'],
			'inputType' => 'fineUploader',
			'exclude' => true,
			'eval' => array(
				'mandatory' => true,
				'storeFile' => true, // Mandatory to store the file on the server
				'extensions' => "jpg, JPG, jpeg, JPEG", // Allowed extension types
				"fieldType" => "radio",
				'maxlength' => 2000000, // Maximum file size
                                "uploadFolder" => "files/uploads"
				) ,
			'sql' => "blob NULL"
			),

**Comment by qzminski** [comment]
I cannot reproduce the issue (develop branch).
