### ISSUE TITLE
Fineuploader im Subpalette einblenden über Checkbox submitObChange=true Handler

### ISSUE THREAD

**Issue by mafudelaptu** [terminal42/contao-fineuploader#19]
Wenn der Fineuploader im Subpalette über den DCA definiert ist und dieses Subpalette über eine Checkbox eingeblendet wird, wird der "Datei hochladen"-Button nicht angezeigt.

Erst durch erneutes Laden der Seite wird der "Datei hochladen" Button angezeigt.

dca:

'palettes' => array(
		'\__selector__' => array('addImages'),
		'default' => 'addImages'
		) ,
	'subpalettes' => array
	(
		'addImages' => 'images'
		),

'fields' => array(
"addImages" => array(
			'label' => & $GLOBALS['TL_LANG']['tl_module']['addImages'],
			'inputType' => 'checkbox',
			'exclude' => true,
			'eval'  => array('submitOnChange'=>true),
			'sql' => "char(1) NOT NULL default ''"
			),
'images' => array(
			'label' => & $GLOBALS['TL_LANG']['tl_module']['images'],
			'inputType' => 'fineUploader',
			'exclude' => true,
			'eval' => array(
				"mandatory" => true,
				"multiple" => true,
				"fieldType" => "checkbox",
				'storeFile' => true, // Mandatory to store the file on the server
				'extensions' => "jpg,JPG,jpeg,JPEG", // Allowed extension types
				'maxlength' => 2000000, // Maximum file size
				) ,
			'sql' => "blob NULL"
			),
		)
);

**Comment by qzminski** [comment]
Fixed in 3f86434.
