### ISSUE TITLE
Feature Request: deep-delete (Lösche Datei auch auf dem Server)

### ISSUE THREAD

**Issue by cyberlussi** [terminal42/contao-fineuploader#20]
Hi,

zur Zeit experimentiere ich damit, eine Galerie mit madeyourday/contao-rocksolid-custom-elements zu erstellen (was mir dank dem Support dort nun gelungen ist). Allein das "Aufräumen" ist noch nicht befriedigend gelöst. Ich habe Sorge, dass der Server nach längerem Gebrauch Dateileichen vorhält, obwohl die darüberliegenden Elemente schon lange gelöscht sind. Soweit ich verstanden haben, ist das Hochladen eine Einbahnstraße. Nach dem erstmaligen Speichern eines Eintrages sind die Dateien im DBAFS (wenn addToDbafs true), ins Zielverzeichnis verschoben und das Feld von contao-fineuploader zeigt die bisher ausgewählten Dateien. Soweit gut. Die Dateien verbleiben aber auf dem Server bis man über die Dateiverwaltung die Einträge löscht. 

Könnte man das javascript hinter ContaoFineUploader.deleteItem() so anpassen, dass die gewählte Datei auch vom Server gelöscht wird? Am besten konfigurierbar (nur aus Liste entfernen / löschen mit Rückfrage / sofort löschen).

Etwas weiter würden folgende Löschanweisungen gehen:
- zusätzlicher "Alle Löschen" button
- wenn ein Eintrag z.B. ein Artikel gelöscht wird, der ein contao-fineuploader Feld beinhaltet, werden alle zugeordneten Dateien mit gelöscht.

Das würde den Kreis schließen und man müsste nicht den Server nach Dateileichen durchsuchen (okay, wäre sicherlich per Script lösbar, aber bliebe ein Workaround).

**Comment by cyberlussi** [comment]
Anmerkungen hierzu?

**Comment by aschempp** [comment]
Falls du deine Aussagen auf Datensätze im Backend beziehst, wäre es wohl korrekt die benötige Lösung selber mit einem `ondelete_callback` im DCA zu realisieren.

Falls es um unvollständige Uploads in `system/tmp` geht, dieser Ordner wird von Contao automatisch monatlich geleert.
