### ISSUE TITLE
Feature Request: dynamischer uploadFolder

### ISSUE THREAD

**Issue by cyberlussi** [terminal42/contao-fineuploader#21]
Hi,

wäre es möglich den UploadFolder dynamisch zu konfigurieren? Nützlich wäre es einen String für

- date() 
oder
- sprintf() mit Referenz auf z.B. ein weiteres Textfeld/Headline/o.ä. des gleichen Eintrages

angeben zu können. Der neue Ordner müsste natürlich auch automatisch angelegt werden. Man hätte so etwas mehr Ordnung auf dem Server und füllt nicht ein Verzeichnis, welches dann hunderte von Dateien beinhaltet.

**Comment by Toflar** [comment]
Contao kann das selbst auch nicht und ich glaube ganz ehrlich, dass das auch eher etwas customized sein sollte. Ich glaube ich vote -1. @aschempp?

**Comment by aschempp** [comment]
Wenn das Widget als DCA-Feld verwendet wird, funktioniert das. Ich vermute aber du benutzt ihn im Formulargenerator?

**Comment by cyberlussi** [comment]
Ich verwende es aktuell mit madeyourday/contao-rocksolid-custom-elements. Das Problem ist wohl, dass kein neues Verzeichnis angelegt wird (ich habe den upload-Basis-Pfad eigentlich freigeschaltet, dass der Webserver dort neue Verzeichnisse anlegen könnte).

**Comment by seomantix** [comment]
@aschempp Würde das als DCA-Feld auch jetzt schon ohne Umbau funktionieren? Würde das nämlich so in der Tat gerade bei einem Modul benötigen. Wie müsste das denn aussehen?

**Comment by aschempp** [comment]
naja, das müsste halt programmiert werden, was bei einem eigenen DCA ja immer geht ;-)
