### ISSUE TITLE
Dateien mit Kommata (,) im Dateinamen werde nicht gespeichert

### ISSUE THREAD

**Issue by Ainschy** [terminal42/contao-fineuploader#22]
Leider musst ich feststellen, das Dateinamen mit Kommata (,) nicht gespeichert werden. Weder über Drag&Drop noch über die Auswahl.

In der Contao Dateiverwaltung werden Dateinamen mit Kommata akzeptiert.

VG
Oliver

**Comment by qzminski** [comment]
Fixed in ce4698d.

**Comment by Ainschy** [comment]
Thanks a lot
