### ISSUE TITLE
Auto submitting whole form after onComplete

### ISSUE THREAD

**Issue by nrunde** [terminal42/contao-fineuploader#23]
I wanna implement an option via the onComplete callback of fineuploader in the frontend, but the onComplete event isn't available through standard implementation.
Could you add an option to extend the onComplete Callback?

**Comment by qzminski** [comment]
Implemented in 34d374f. In your custom form template you can now add the callbacks:

```php
<script>
    ContaoFineUploader.init(document.getElementById('<?php echo $this->strId; ?>_fineuploader'), {
        ...
        onCompleteCallback: function (id, name, result) {
            console.log(id);
            console.log(name);
            console.log(result);
        },
        ...
    }, <?php echo $this->config; ?>);
</script>
```
