### ISSUE TITLE
Maxlength (and minlength) can be zero

### ISSUE THREAD

**Issue by aschempp** [terminal42/contao-fineuploader#27]
In the form generator, an "empy" value for `minlength` and `maxlength` equals "ignore this". Currently if maxlength is 0, no files can be uploaded due to file size limit.

**Comment by qzminski** [comment]
Fixed in 0fb3fa7.

**Comment by qzminski** [comment]
I think it does not matter for minlength as 0 means pretty the same as it unlimited in this case.

**Comment by aschempp** [comment]
Probably, dunno how fineuploader handles that ;-)
