### ISSUE TITLE
Implement minlength validation on client side

### ISSUE THREAD

**Issue by aschempp** [terminal42/contao-fineuploader#28]
Requires Haste 4.12 for new `Haste\Util\FileUpload`.

**Comment by aschempp** [comment]
Haste updated in https://github.com/codefog/contao-haste/commit/e4d37edf9eb8334aea3c18019681559a83521c54

**Comment by qzminski** [comment]
Implemented in e990a27.

**Comment by qzminski** [comment]
Haste dependency was fixed in c6490905a5cde4013c0d3d8fb4fd4ec3b17fce76.

**Comment by aschempp** [comment]
how do we validate minimum length on chunking now?

**Comment by qzminski** [comment]
Minimum length of a chunk? ;-)

**Comment by aschempp** [comment]
No, minimum length of the whole file after all chunks are combined…

**Comment by qzminski** [comment]
I don't know if it's validated at all, even for maxlength...

**Comment by aschempp** [comment]
It must be… we should add a new issue then.
