### ISSUE TITLE
Progress bar display issue

### ISSUE THREAD

**Issue by aschempp** [terminal42/contao-fineuploader#35]
If I select an invalid file type (e.g. PSD but only JPEG is allowed), the progress bar container becomes visible and won't hide.

**Comment by qzminski** [comment]
That's the default behavior of FineUploader which you can also see in the official demo:

http://fineuploader.com/demos.html

Although there it is floating right so not really noticeable to the user as it does not push down the button.

**Comment by aschempp** [comment]
Then we should probably file a bug (or check if it's already there)?

**Comment by qzminski** [comment]
I think it's already reported here https://github.com/FineUploader/fine-uploader/issues/1600
