### ISSUE TITLE
Upload failure due to image size does not hide progress

### ISSUE THREAD

**Issue by aschempp** [terminal42/contao-fineuploader#37]
When a picture is too big to upload it will result in a red upload box. Even though the upload is "finished", it still shows the last progress and the cancel button.

![bildschirmfoto 2016-07-15 um 12 33 21](https://cloud.githubusercontent.com/assets/1073273/16871640/560e93d4-4a88-11e6-8507-73eda1aac71a.png)

**Comment by qzminski** [comment]
That's also the default behavior of FineUpload. I can hide the size information and cancel button via CSS though.

**Comment by aschempp** [comment]
Bug report?

**Comment by qzminski** [comment]
That's not a bug in my opinion. FineUploader starts uploading the chunks and with each chunk sent it updates the HTML to display the progress. When the first chunk that allows to determine image size is uploaded its size is checked and if it exceeds the limit, the server side simply returns an error response. Upon the error FineUpload immediately stops the upload and displays the error. The rest of the content is kept from the "right before upload" state. The cancel button is also perfectly fine, you may want to cancel the failed upload.

Frankly it's up to custom preferences whether it should be kept or not and that can be changed easily via CSS.

**Comment by aschempp** [comment]
I disagree. The upload already **is** cancelled due to the error message, so the button does not make sense. Neither does the progress, because there's no progress if the upload has been cancelled…
