### ISSUE TITLE
Invalid title on upload button

### ISSUE THREAD

**Issue by aschempp** [terminal42/contao-fineuploader#42]
There's a `title` attribute on the submit button that says "file upload". I don't think that's indented or useful 😂

**Comment by qzminski** [comment]
That button is generated by the FineUploader itself, no influence on it.

**Comment by aschempp** [comment]
We should file a bug report then…

**Comment by qzminski** [comment]
See https://github.com/FineUploader/fine-uploader/issues/1526. The title attribute can be customized but never removed.

**Comment by aschempp** [comment]
> It works when explicitly defined as empty string.

Either we should do that or give it a meaningful label (we might already have one?)

**Comment by qzminski** [comment]
Fixed in 1434aeb.
