### ISSUE TITLE
'directUpload' => true wird ignoriert

### ISSUE THREAD

**Issue by mp-itconsulting** [terminal42/contao-fineuploader#44]
Egal ob 'true' or 'false', die Datei(en) werden immer erst ins system/tmp geladen und erst nach dem Speichern in das angegebene Zielverzeichnis verschoben. Hier meine DCA-Konfiguration:

  (
        'storeFile'         => true,
        'multiple'          => true,
        'uploadFolder'      => $strTargetFolder, (wird vorher ermittelt/gesetzt)
        'uploaderLimit'     => 10,
        'addToDbafs'        => true,
        'extensions'        => 'pdf,xls,xlsx,xlsm,doc,docx,ppt,pptx,zip,mov,mp3,mp4',
        'minlength'         => 1024,
        'maxlength'         => 2048000,
        'doNotOverwrite'    => false,
        'maxConnections'    => 3,
        'directUpload'      => true,
    ),

**Comment by fritzmg** [comment]
Kann ich bestätigen (bspw. mit [dieser Konfiguration](https://gist.github.com/fritzmg/5fa00ce436a0308f2c7c) für news easer + `directUpload => true`).

**Comment by mp-itconsulting** [comment]
Ich hab es mit der letzten/aktuellen Version und Contao 3.5.15 getestet

**Comment by qzminski** [comment]
I know it's a bit late for this but is it still reproducible in 2.1?

**Comment by fritzmg** [comment]
Yes, I just tried with `2.1.2`. The file was uploaded to `/system/tmp` and then copied or moved to `'uploadFolder'`.

**Comment by qzminski** [comment]
Can you try 9753bc9 please?

**Comment by fritzmg** [comment]
Works as far as I tested 👍

**Comment by qzminski** [comment]
Perfect, I am releasing 2.1.3 then.
