### ISSUE TITLE
Only one filename stored in Session data when uploading multiple files

### ISSUE THREAD

**Issue by c-zehnter** [terminal42/contao-fineuploader#46]
I want to access the filenames and -paths of all files when uploading multiple files. I am using a custom template on the confirmation page after submitting the form. The problem is, that the `["FILES"]` session array (which seems to be created by fineuploader) is always empty after submitting. When I try to access the data of the uploader element in `["FORM_DATA"]`, only the first filename is available. Is this some sort of bug or am I just using it wrong? I'd appreciate any help!

```
["FORM_DATA"]["fineuploader"]=>
    string(22) "files/data/filename.xy"

 ["FILES"]=>
  array(0) {
  }
```

**Comment by qzminski** [comment]
Are you sure you have set the `multiple` attribute to true? Also is the problem still reproducible in 2.1?
