### ISSUE TITLE
Feature Request: Show only filename instead path

### ISSUE THREAD

**Issue by christianbarkowsky** [terminal42/contao-fineuploader#54]
Sometimes it's better to show only the filename instead the full path.
Maybe you can make it configurable.

`    'eval' => array  
    (  
        'onlyShowFilename' => true,  
        ...  
`

<img width="286" alt="bildschirmfoto 2019-01-23 um 13 37 09" src="https://user-images.githubusercontent.com/1230547/51607102-07ab8900-1f14-11e9-9627-ae2d2ca84bea.png">

**Comment by qzminski** [comment]
This will be available in 3.0.
