### ISSUE TITLE
JS typeError after creating fine uploader field in backend

### ISSUE THREAD

**Issue by havutcuoglu** [terminal42/contao-fineuploader#55]
After creating an fine upload field in backend, the Console displays TypeError. 
The error is reproducible under Contao version 4.4.35 and version 4.6.6 to.

<img width="1763" alt="Bildschirmfoto 2019-04-05 um 08 55 42" src="https://user-images.githubusercontent.com/11348417/55610280-e3c1ba80-5782-11e9-9b90-f86c5bef516a.png">

**Comment by qzminski** [comment]
Fixed in 5f74e3e.
