### ISSUE TITLE
Files containing a comma in the filename stay in the tmp folder and are neither attached to the email nor copied to the target folder

### ISSUE THREAD

**Issue by bopsoid** [terminal42/contao-fineuploader#57]
Hello,

I already found this:

https://github.com/terminal42/contao-fineuploader/commit/ce4698d8afd859d9bc57153911e1b7cee30772cb

so I thought the problem was solved ... but still it's not working for me.

I'm using Contao 4.8.x + Notification Center

Also the transmitted form variable is not really useful if a filename contains a comma, cause the filename with the comma then corrupts the possibility to further analyse the paths of the uploaded files, i.e. 

File1.zip 
File2,2.zip

Return value from the form: File1.zip,File2,2.zip

If I try to separate this string for further use in a module, I'll get three files:

File1.zip
File2
2.zip

Did I miss something or is the bug still there?

Thanks for checking and regards,
Boris :-)

**Comment by qzminski** [comment]
I think this should be fixed in 3.0, which has been released today.
