### ISSUE TITLE
Can't upload image on the frontend

### ISSUE THREAD

**Issue by raynor84** [terminal42/contao-fineuploader#60]
The Upload is working fine on the backend. But for some reason it can't upload on the frontend.

Here is my Config:
```
``$GLOBALS['TL_DCA']['tl_member']['fields']['gallery'] = array
(
    'label'                   => &$GLOBALS['TL_LANG']['tl_table']['gallery'],
    'exclude'                 => false,
    'inputType'               => 'fineUploader',
    'eval'                    => array
    (
        //'storeFile'         => true,                // Mandatory to store the file on the server
        //'multiple'          => true,                // Allow multiple files to be uploaded
        //'uploadFolder'      => 'files',     // Upload target directory (can also be a Contao file system UUID)
        //'useHomeDir'        => true,                // Upload to the FE member home directory (overrides "uploadFolder", can also be a Contao file system UUID)
        //'uploaderConfig'    => "['debug': true]",   // Custom uploader configuration that gets merged with the other params
        //'uploaderLimit'     => 4,                   // Maximum files that can be uploaded
        //'addToDbafs'        => true,                // Add files to the database assisted file system
        //'extensions'        => 'jpg, jpeg, png',           // Allowed extension types
        //'maxlength'         => 2048000,             // Maximum file size (is ignored if you use chunking!)
        //'maxWidth'          => 800,                 // Maximum width (applies to images only)
        //'maxHeight'         => 600,                 // Maximum height (applies to images only)
        //'doNotOverwrite'    => true,                // Do not overwrite files in destination folder
        //'uploadButtonLabel' => 'Upload images',     // Custom upload button label

        //'maxConnections'    => 3,                    // Maximum allowable concurrent requests
		//'feViewable' => true, 
		//'feEditable'=>true, 
		//"tl_class" => "w50 wizard",

        // Upload the files directly to the destination folder. If not set, then the files are first uploaded
        // to the temporary folder and moved to the destination folder only when the form is submitted
        //'directUpload' => true,
        
        // Set a custom thumbnail image size that is generated upon image upload  
        //'imageSize'         => [160, 120, 'center_center'],

        // You can also use the default features of fileTree widget such as:
        // isGallery, isDownloads

        // The "orderField" attribute is not valid (see #9)
    ),
    'sql'                     => "blob NULL"
);
```

![fehler](https://user-images.githubusercontent.com/4583529/80869817-c96a5100-8ca2-11ea-9edc-108f453c524f.png)

**Comment by qzminski** [comment]
Looks like you commented out the whole configuration in `eval`. This is probably the reason it does not work.

**Comment by raynor84** [comment]
I also have two other fields which don't work either:

`$GLOBALS['TL_DCA']['tl_member']['fields']['profilepic'] = array
(
    'label'     => &$GLOBALS['TL_LANG']['tl_member']['profilepic'],
    'exclude'   => true,
    'inputType' => 'fineUploader',
    'eval'      => array('storeFile'=>true, 'useHomeDir'  => true,  'mandatory'=>false, 'uploadFolder'      => 'files/user/','feEditable'=>true, 'feViewable'=>true, "tl_class" => "w50 wizard", 'feGroup'=>'address', 'extensions' => 'jpg, jpeg, png', 'addToDbafs'        => true,),
    'sql'                     => "blob NULL"
);
$GLOBALS['TL_DCA']['tl_member']['fields']['verifypic'] = array
(
    'label'     => &$GLOBALS['TL_LANG']['tl_member']['verifypic'],
    'exclude'   => true,
    'inputType' => 'fineUploader',
    'eval'      => array('storeFile'=>true, 'useHomeDir' => true,'uploadFolder'      => 'files/user/',  'mandatory'=>false, 'feEditable'=>true, 'feViewable'=>true, "tl_class" => "w50 wizard", 'feGroup'=>'address', 'extensions' => 'jpg, jpeg, png', 'addToDbafs'        => true,),
    'sql'                     => "blob NULL"
);`

**Comment by qzminski** [comment]
1. The extensions should probably have no space between the names (`jpg, jpeg, png` –> `jpg,jpeg,png`).
2. You enabled the `useHomeDir` flag which requires a home directory set for the currently logged in member. Does he have one? Also in this case the `uploadFolder` is irrelevant.

**Comment by raynor84** [comment]
1) I removed the spaces.
2) The user get's automatically assigned to a homedir. When he registers. The failure happens at the registration process. But creating a new user in the backend works perfectly fine.

**Comment by qzminski** [comment]
User home directory is not yet present when you upload a file during the registration process. You should probably take down the `useHomeDir` flag, upload the files to a temporary place and process them afterwards using the `$GLOBALS['TL_HOOKS']['createNewUser']` hook. I think that should solve your problem.

**Comment by raynor84** [comment]
But this happens also when I login and want to update a profile. The Upload fails on start. I guess it doesn't upload into the temp-folder.

**Comment by qzminski** [comment]
I see, can you please check the XHR response content in the Network tab of your devtools?

**Comment by raynor84** [comment]
![xhr](https://user-images.githubusercontent.com/4583529/81585509-8e5bd200-93b4-11ea-82ab-6b2e03f98d4d.jpg)

I was trying to upload an image. while this network view was present.

**Comment by qzminski** [comment]
Great so now you have to click on the `user.html` item and print screen the response it returned.

**Comment by raynor84** [comment]
the response is an html-output of the current page...

**Comment by raynor84** [comment]
so any idea why it's not working?

**Comment by qzminski** [comment]
We have just released version 3.0, which was lurking around for some time. Please upgrade and see if it solves your problem as 2.x is now no longer supported.

**Comment by raynor84** [comment]
It's working now thx. One last question, how do i read from the database or write the file into the database

**Comment by qzminski** [comment]
To write a file into the database you have to enable the `addToDbafs` flag in field configuration. Afterwards you read it e.g. using `FilesModel::findByPk($uuid)`.
