### ISSUE TITLE
Drop area not visible

### ISSUE THREAD

**Issue by PaoloB** [terminal42/contao-fineuploader#61]
The drop area not visible by default.
In the template file fineuploader_uploader.html5 the class qq-hide-dropzone is inserted incorrectly.

Line 6

` <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
        <span class="qq-upload-drop-area-text-selector"><?= $GLOBALS['TL_LANG']['MSC']['fineuploader.drop'] ?></span>
    </div>`

You can check?
Thanks

**Comment by ameotoko** [comment]
This is not a class. According to FineUploader [docs](https://docs.fineuploader.com/branch/master/features/drag-and-drop.html), `qq-hide-dropzone` is an attribute, making drop area invisible by default.

To make drop area visible, simply remove this attribute from the template.

**Comment by aschempp** [comment]
Since [the fineuploader script itself is not being developed anymore](https://github.com/FineUploader/fine-uploader/issues/2073), we're not planning to add new features to our extension. I'm therefore closing this issue.
