### ISSUE TITLE
Kein Upload möglich bei Dateinamen die ein "+" enthalten

### ISSUE THREAD

**Issue by Floxn** [terminal42/contao-fineuploader#70]
Es wird keine Datei hochgeladen, das ein "+" im Namen beinhaltet. 
Wenn das Feld als Pflichtfeld gekennzeichnet ist, wird auch ein absenden die Meldung gebracht, das keine Datei ausgewählt ist.

Getestet bei Contao 4.9.5 und Finuploader Version 3.1.2

**Comment by ngdot** [comment]
Stimmt, gleiches Problem mit der aktuellsten Version unter 4.9.9.

**Comment by aschempp** [comment]
das scheint wohl ein Problem des Fineuploader Scripts. Leider wird Fineuploader nicht mehr gepflegt (https://github.com/FineUploader/fine-uploader/issues/2073) daher würde ich davon ausgehen dass sich das nicht ändern lässt 😞

**Comment by aschempp** [comment]
Since [the fineuploader script itself is not being developed anymore](https://github.com/FineUploader/fine-uploader/issues/2073), we're not planning to add new features to our extension. I'm therefore closing this issue.
