### ISSUE TITLE
Operation in Internet Explorer

### ISSUE THREAD

**Issue by 463** [terminal42/contao-fineuploader#72]
The content element do not work in IE (also IE11). It fails with

`SCRIPT438: Das Objekt unterstützt die Eigenschaft oder Methode "from" nicht`

in [handler.js](https://github.com/terminal42/contao-fineuploader/blob/master/src/Resources/public/handler/handler.js). In line 169 and later `Array.from()` is used. 

This method is not supported by the Internet Explorer in [general](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Browser_compatibility). But the [polyfill / workaround on this page](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill) copied to an explicit js-file and linked in the header as an additional `<head>`-tag (e.&nbsp;g. `<script src="files/js/array_from.js"></script>`) allows the operation also in IE.

This manual integration of the polyfill should be replaced by a standard integration at all time or a general replacement of `Array.from()`.

**Comment by fritzmg** [comment]
I do not think that this is something that should be integrated or changed within the extension. If you still need to support IE 11 for some reason, then you can simply use the workaround you found.

**Comment by aschempp** [comment]
I agree with @fritzmg. IE is dead.
