### ISSUE TITLE
Konflikt mit mpforms & ajaxform

### ISSUE THREAD

**Issue by sfx12** [terminal42/contao-fineuploader#74]
Leider geht der fineuploader in Verbindung mit mehrseitigen Formularen + ajaxform **nicht** (auch von euch die Extensions)

**Mehrseitig ohne ajaxform -> geht
ajaxform ohne mehrseitig -> geht
mehrseitig & ajaxform -> geht nicht**

es kommt laut log auch zu keiner Fehlermeldung, es wird lediglich der uploader im FE nicht angezeigt!

**Comment by fiedsch** [comment]
Findet sich im Output (Console) des Browsers etwas (z.B. JS-Fehler) dazu?

**Comment by sfx12** [comment]
nein, absolut nichts.. der generierte output wird nicht "generiert" .. das passiert nur wenn ich den uploader nach einem Seitenumbruch, also ab Seite 2 einfüge.

Irgendwas beisst sich da mit "ajax"

**Comment by sfx12** [comment]
Kann niemand helfen!?

**Comment by aschempp** [comment]
https://www.terminal42.ch/de/open-source.html 😊

**Comment by aschempp** [comment]
Ajaxform has been abandoned for Contao 5, I'm therefore closing this issue since we don't plan to fix anything in this regard.
