### ISSUE TITLE
Simple Token Ausgabe ohne Pfadangabe

### ISSUE THREAD

**Issue by dthomasge** [terminal42/contao-fineuploader#75]
Hallo,

der Fine-Uploader ist eine wirklich tolle Erweiterung, aber dennoch habe ich 2 Probleme damit. Bei meinen bisherigen Recherchen dazu konnte ich nichts passendes diesbezüglich finden.

Generiert man über das Notification Center mittels Simple Tokens ##form_upload## für die E-Mails, dann wird der Dateiname mit dem kompletten Pfad der Dateiverwaltung ausgegeben. Gibt es einen Schalter oder eine andere Möglichkeit für den Simple Token, damit die Ausgabe vom Pfad unterbunden wird?

Wenn man versucht die Dateinamen auf der Bestätigungsseite mittels Insert Tag {{post::upload}} auszugeben, dann wird nichts ausgegeben. Alle Inhalte der anderen Eingabefelder werden ordnungsgemäß ausgegeben. Gibt es eine Möglichkeit die Dateinamen der ausgewählten Dateien auf einer Webseite auszugeben? Auch hier soll kein Pfad der Dateiverwaltung angezeigt werden, nur der Dateiname alleine.

Gruß
Thomas

**Comment by aschempp** [comment]
ich denke das dürfte mit https://github.com/terminal42/contao-notification_center/pull/375 erledigt sein 😎
