### ISSUE TITLE
Übersetzung innerhalb von Dialogboxen in English auf deutschen Seiten

### ISSUE THREAD

**Issue by contaoacademy** [terminal42/contao-fineuploader#76]
- Contao: 4.9.11
- Extension: 3.1.5

Im Frontend werden die Fehlermeldung innerhalb der Overlays immer in Englisch ausgeben.

![screen-20210127_SBiLWHj7](https://user-images.githubusercontent.com/23719181/106016848-2b37da00-60c0-11eb-894a-493d0dde3032.jpg)

**Comment by martin-netprofit** [comment]
Hab das gleiche Problem : /

Contao: 4.10.5
Extension: 3.1.4
