### ISSUE TITLE
isotope-core 2.7.0 conflicts with terminal42/contao-fineuploader 3.1.7

### ISSUE THREAD

**Issue by codesache** [terminal42/contao-fineuploader#79]
Hallo zusammen,

mir wird in ein bestehende lokale Installation vom contao-fineuploader mit Isotope ein Konflikt über den Manager ausgegeben.

Zum Einsatz unter Mac mit MAMP kommt eine Contao 4.9.12, PHP 7.2 und Isotope in der Version 2.7.0.

  Problem 1
    - isotope/isotope-core 2.7.0 conflicts with terminal42/contao-fineuploader 3.1.7.
    - isotope/isotope-core 2.7.0 conflicts with terminal42/contao-fineuploader 3.1.6.
    - isotope/isotope-core 2.7.0 conflicts with terminal42/contao-fineuploader 3.1.5.
    - isotope/isotope-core 2.7.0 conflicts with terminal42/contao-fineuploader 3.1.4.
    - isotope/isotope-core 2.7.0 conflicts with terminal42/contao-fineuploader 3.1.3.
    - isotope/isotope-core 2.7.0 conflicts with terminal42/contao-fineuploader 3.1.2.
    - isotope/isotope-core 2.7.0 conflicts with terminal42/contao-fineuploader 3.1.1.
    - isotope/isotope-core 2.7.0 conflicts with terminal42/contao-fineuploader 3.1.0.
    - isotope/isotope-core is locked to version 2.7.0 and an update of this package was not requested.
    - Root composer.json requires terminal42/contao-fineuploader ^3.1 -> satisfiable by terminal42/contao-fineuploader[3.1.0, ..., 3.1.7].

---

Ich habe dann die Version 2.1.3 vom fineuploader manuell eingetragen und konnte damit die Installation abschließen.

Mir wurde dann die Version 2.6.0 vom Isotop Core installiert!

Gibt e mit dem neuen Isotop 2.7.0 etwas zu beachten was die Erweiterungen angeht?

Viele Grüße

Markus

**Comment by fritzmg** [comment]
This is a requirement set by `isotope`, not by `contao-fineuploader`, see https://github.com/isotope/core/blob/e3b77e13b37b38429566d3e50318befc1561f989/composer.json#L58

In order to be able to use `isotope` together with `contao-fineuploader`, you need to require `^2.0` of `contao-fineuploader`.

**Comment by codesache** [comment]
Danke für die Rückmeldung!
