### ISSUE TITLE
Warning: foreach() argument must be of type array|object, null given

### ISSUE THREAD

**Issue by 1stof8** [terminal42/contao-fineuploader#85]
I updated to Contao 4.13.1 // Fine Uploader 3.2.0

When I try to edit the form this error appears
`Warning: foreach() argument must be of type array|object, null given`

Frontend this error appears
`Warning: Undefined array key "messages"`

**Comment by fritzmg** [comment]
Use the debug mode and post the stack trace of each of these.

**Comment by aschempp** [comment]
likely fixed in b38fe8b2df44bb89aa2a8cab9a534858710eb359
