### ISSUE TITLE
Feature: Option to add file Link 

### ISSUE THREAD

**Issue by Metis77** [terminal42/contao-fineuploader#93]
Contao 4.13
PHP 8.1

In the email sent, only the relative path to the files are listed.
Having an option to add the complete URL to link directly to the file would help a lot.

If there is not already a way of doing this (?) that would be an awesome feature.

This issue may be related to #77

**Comment by operatorone** [comment]
It would be most appreciated to have the ability to add a link.

**Comment by tsarma** [comment]
I too wish it functions like a normal Contao Upload File, where Contao provides a link to the file at the bottom of email text.

This is due not availability of `$_SESSION['FILES']`, when using `fineuploader` thus the following lines of code from Contao File.php is not executed.

```php
// Attach uploaded files
if (!empty($_SESSION['FILES']))
{
    foreach ($_SESSION['FILES'] as $file)
    {
        // Add a link to the uploaded file
        if ($file['uploaded'] ?? null)
        {
            $uploaded .= "\n" . Environment::get('base') . StringUtil::stripRootDir(\dirname($file['tmp_name'])) . '/' . rawurlencode($file['name']);
            continue;
        }

        $email->attachFileFromString(file_get_contents($file['tmp_name']), $file['name'], $file['type']);
    }
}

$uploaded = trim($uploaded) ? "\n\n---\n" . $uploaded : '';
```

https://github.com/contao/contao/blob/4.13/core-bundle/src/Resources/contao/forms/Form.php#L458-L473

**Comment by fritzmg** [comment]
This is a regression caused by https://github.com/terminal42/contao-fineuploader/pull/92
In that PR the session usage was removed. However, for Contao 4.13 compatibility, this needs to stay.
